### ISSUE TITLE
Alumni Portraits

### ISSUE THREAD

**Issue by ccauet** [pep-dortmund/homepage#100]
* Durch http://physik.tu-dortmund.de/cms/de/Studium/Zusaetzliche-Beitraege/Alumni-erzaehlen/index.html bin ich gerade auf die Idee gekommen, dass wir solche Alumni-Portraits auch auf die PeP-Homepage packen könnten.
* Das wäre auch ein netter Aufhänger sich mal wieder gezielt an einige Alumni zu wenden um nach einem kurzen Text zu fragen. 

* Wie findet ihr die Idee, gebt mir ein 👍 oder ein 👎 
* Fühlt sich jemand berufen?

**Comment by jamueller** [comment]
Find ich gut!

Da ich ja auch Alumnibeauftragte bin, werde ich wohl berufen fühlen müssen ;-)

LG,
Janine

**Comment by ccauet** [comment]
@jamueller Ich versuche zu unterstützen. Wir können ja mal mit ner Liste von Alumni anfangen, und uns diese dann aufteilen um sie anzuschreiben.

**Comment by MaxNoe** [comment]
@marschmitz macht gerade was ähnliches für die neue Erstsemesterbroschüre. Unter anderem mit Marlene und Christian Jung

**Comment by marschmitz** [comment]
Jau ich habe bisher schon einige angeschrieben und kann gerne da mal nachfragen, ob die sich auch auf die Homepage stellen lassen.
Ich denke das sollte kein Problem sein wenn es sowieso in der Broschüre auftaucht.
Hab auch noch weitere Alumni, die ich aktivieren könnte.

**Comment by ccauet** [comment]
@MaxNoe Ich habe davon gehört ;) 

@marschmitz Das wäre sehr gut. Vielleicht können wir auch die Fragen die schon drin stehen und die einfach mit dazu nehmen?

**Comment by marschmitz** [comment]
Okay ich schreib die mal an. Sollen wir das dann in einer Art Ahnentafel verfassen, in der die Leute berichten? 
Vielleicht möchte der ein oder die andere den Text auch nochmal aktualisieren.

**Comment by ccauet** [comment]
> Okay ich schreib die mal an. Sollen wir das dann in einer Art Ahnentafel verfassen, in der die Leute berichten?

Ich finde das Steckbriefformat eigentlich gar nicht schlecht. Wir können es "Hall of Fame" nennen ;) 

> Vielleicht möchte der ein oder die andere den Text auch nochmal aktualisieren.

Ja, unbedingt

-----------

@jamueller Was meinst du, klingt das gut?

**Comment by jamueller** [comment]
Hi,

sorry war etwas afk (oh...wie lange habe ich das nicht mehr benutzt...:-D) 

Ich finde das Steckbriefformat auch sehr gut. Ahnentafel finde ich ein ziemlich hartes Wort...Hall of fame ist besser ;-)


Also alles sehr sehr gut!

**Comment by hmoldenhauer** [comment]
Kann nun geschlossen werden, da wir nun eine Wall of Fame haben
