### ISSUE TITLE
Drop down menu for Stipendien

### ISSUE THREAD

**Issue by beckstev** [pep-dortmund/homepage#114]
We want to restructure the Stipendien site.
So it is easier to acess/view the new Summer School part.

**Comment by hmoldenhauer** [comment]
should work as implemented on branch. Chould somebody check this @MaxNoe or @bixel?

**Comment by MaxNoe** [comment]
If you have something ready for review, you should open a Pull Request.

**Comment by hmoldenhauer** [comment]
we still need some questions to be answered. But once done we'll open a Pull Request

**Comment by MaxNoe** [comment]
Just open it and say it is not ready yet

**Comment by bixel** [comment]
You could prefix the PR with *WIP: blabla*
