### ISSUE TITLE
Information check - Going Abroad

### ISSUE THREAD

**Issue by beckstev** [pep-dortmund/homepage#115]
- [x]  mention - Leisure center, is it free?

- [x] check time you can stay in the USA, after you complete the research project

- [x]  do we pay the health insurance for the USA ?

- [x] verify application deadline

- [x]  create a QR-Code

**Comment by hmoldenhauer** [comment]
Checked J1. See https://j1visa.state.gov/basics/common-questions/ for reference

**Comment by hmoldenhauer** [comment]
yes, we pay the health insurance, as mentioned in our 'Kostenaufstellung'

**Comment by hmoldenhauer** [comment]
Do we need a QR-Code?

**Comment by beckstev** [comment]
QR-Code for the poster.
Fabi has made one

**Comment by hmoldenhauer** [comment]
Leisure Centre will cost 65$, but is included in our calculations.
