### ISSUE TITLE
Footer looks differently

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/homepage#169]
After merging #154 the footer looks different when building locally vs. building with travis. Maybe due to some build environment changes?

as-is:

![screen shot 2018-03-01 at 11 21 09](https://user-images.githubusercontent.com/2527718/36839540-ac85f8ae-1d42-11e8-8388-e050027f344c.png)

as it should be:

![screen shot 2018-03-01 at 11 21 37](https://user-images.githubusercontent.com/2527718/36839577-bb7aa13e-1d42-11e8-99e5-fbd637d33cba.png)

**Comment by MaxNoe** [comment]
Looks fine for me, cache reload?

**Comment by bixel** [comment]
Yeah it depends on the browser. FF shows the bullet points just next to the text.

**Comment by jamenne** [comment]
<img width="284" alt="footer" src="https://user-images.githubusercontent.com/14741470/38546677-8caadf60-3cad-11e8-883f-ed945560eb9e.png">
Facebook and Twitter buttons do not have an icon

**Comment by bixel** [comment]
lets wait for #172 to be merged. I wouldn't understand why this helps but thats the only difference between my setup and the master version.

**Comment by bixel** [comment]
I realized that this issue is not fixed actually :-(
