### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by maxnoe** [pep-dortmund/homepage#18]
Right now the files are for example indented inconsistently with spaces and tabs.

We should agree on a style guide and follow it.

Any suggestions?

**Comment by bixel** [comment]
https://google.github.io/styleguide/htmlcssguide.xml
But I think we could be lazy with that. So just use the new style when actually updating some files.

**Comment by bixel** [comment]
I'll add some words about this in the CONTRIBUTING.md
