### ISSUE TITLE
Double pasted sentence in: "Wall of Fame"

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage#192]
https://github.com/pep-dortmund/homepage/blob/0464e4b6e86cf1cb4d422b4fa95b637ca7d6a7a2/ueber_uns/wall_of_fame.html#L11-L18

Line 11 and line 18 start with the same sentence but it does not seem to belong into line 18.
I already have it fixed, but I am not yet allowed to push to this repo. :wink:

**Comment by bixel** [comment]
Thanks! I've added you to the group, feel free to open the MR with the fix :-)
