### ISSUE TITLE
Webseite auf Neue Geschäftsführung überprüfen

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage#195]
Ich habe gerade keine Zeit, daher nur ein Issue. Die https://pep-dortmund.org/mitmachen.html muss aktualisiert werden, vermutlich auch ein paar andere Seiten auf der Homepage

**Comment by bixel** [comment]
Das sollte mit #214 und #204 geschlossen worden sein. `grep -r ...` schlägt zumindest nicht mehr an ;-)
