### ISSUE TITLE
Person eingetragen für "Verantwortlich für den Inhalt nach §55 Abs. 2 RStV"

### ISSUE THREAD

**Issue by alexbirne** [pep-dortmund/homepage#217]
hier sollten wir eine Lösung finden wer da eingetragen wird - ich denke Thorben ist nur noch bedingt korrekt (mindestens die Adresse ist falsch), und es handelt sich noch um ein Relikt aus den ersten Tagen der neuen Homepage. 
Außerdem würde ich sagen, dass wir da eine Policy finden sollten, nach der diese Person bestimmt wird, denn einträge auf der Homepage machen viele Leute. Persönlich würde ich es dem VP Öffentlichkeitsarbeit als "aufgabe" geben, die Posts regelmäßig auf unerwünschte Inhalte zu überprüfen und entspr. an dieser Stelle in der Verantwortung zu stehen.

**Comment by ccauet** [comment]
Ich schaue asap rein

**Comment by ccauet** [comment]
@alexbirne 

> Persönlich würde ich es dem VP Öffentlichkeitsarbeit als "aufgabe" geben, die Posts regelmäßig auf unerwünschte Inhalte zu überprüfen und entspr. an dieser Stelle in der Verantwortung zu stehen.

Das wäre von meiner Seite grundsätzlich erstmal ok. Wenn ich (bzw. @Vanessa-Mueller) allerdings persönlich die Verantwortung für Inhalte auf der Seite tragen, müssen wir über den Modus nachdenken mit dem PR durchgeführt werden. Ganz streng ausgelegt, dürften dann inhaltliche Änderungen nur vorgenommen werden wenn ich das ok gebe. Also den PR approve.

Das würde ich gerne klären bevor mein Name da steht. Würde mir darüber hinaus aber auch eine gute Gelegenheit geben von Remote aktiv mitzuwirken.

**Comment by alexbirne** [comment]
@ccauet 
ja, verstehe ich und stimme ich absolut zu - um etwas mehr Redundanz zu schaffen was Abwesenheiten o.ä. angeht kann man da vlt. zwei Personen eintragen, sodass dann du oder @Vanessa-Mueller die requests approved können?!

@bixel, @lena-lin, @marschmitz  
kann ja vlt auf die Agenda für die nächste VS um eine solche Entscheidung etwas "globaler" zu treffen/zu diskutieren?!

**Comment by bixel** [comment]
Ich sehe @ccauet‘s Punkt, würde es aber nicht so streng interpretieren. Ich könnte mir vorstellen, dass wir unsere contributing.md ein wenig überarbeiten und die von @ccauet und @Vanessa-Mueller absegnen lassen. Jeder der einen PR aufmacht, wird vorher darauf hingewiesen, sich an diesem Dokument orientieren zu müssen bzw. die inhaltliche policy zu befolgen. Danach können wir mit PRs so weitermachen wie bisher. Wenn es Unklarheiten gibt können wir einzelne Änderungen blockieren bzw. nicht approven bis die nach §55 Blabla Verantwortlichen, also dann @ccauet und @Vanessa-Mueller eine Entscheidung treffen. So oder so ähnlich könnte ich mir den Prozess jedenfalls gut vorstellen.
Da ich die nächsten 2 VS nicht dabei sein werde habe ich das jetzt mal hier formuliert :-) ich finde es jedenfalls super, wenn ihr euch auf diese Art und weise auch per Remote einbringen könnt. Danke @alexbirne fürs issue aufmachen 👍

**Comment by bixel** [comment]
Closed as discussed in #274 :-)
