### ISSUE TITLE
Stipendien

### ISSUE THREAD

**Issue by marschmitz** [pep-dortmund/homepage#224]
Die Information zur Bewerbung für die Initiativstipendien beziehen sich noch auf den alten Vorstand.  Auch bei Going Abroad steht unten noch Henning als Ansprechpartner drin.

**Comment by beckstev** [comment]
Ich hab gerade auch noch mal drüber gelesen und folgende Anmerkungen: 

- [ ] Es muss angepasst werden, Wann das Programm statt findet 

- [ ] Man ist in einem Einzelzimmer untergebracht und nicht in einem Doppelzimmer

- [ ]  Der Zielflughafen des Hinfluges kann auch abgesprochen werden. Und man kann auch vor dem Visa in die USA und sich das Land anschauen

- [ ] Die Krankenversicherung wird nicht übernommen, zumindest nicht direkt

- [ ] Datum des Bachelorabschlusses muss geändert werden

- [ ] Alle Stichpunkte sollten mit einem Großbuchstaben beginnen

- [ ] Die Bewerbungsfrist muss angepasst werden

Außerdem würde ich nicht  

>  bei einem Vorstandsmitglied im Büro

schreiben sondern _bei uns im Büro_. Vorstandsmitglied klingt abschreckend.

**Comment by hmoldenhauer** [comment]
@beckstev @bixel Ich habe die Änderungen mal eingebaut, bitte schaut kurz drüber und merged das dann ;)

**Comment by bixel** [comment]
Hi @hmoldenhauer, kannst du einen neuen PR mit den Änderungen aufmachen?

**Comment by hmoldenhauer** [comment]
@bixel sind schon eingebaut und auf der Homepage. Allerdings ist mir gerade noch ein Fehler aufgefallen

**Comment by bixel** [comment]
Ok dann schließe ich das issue jetzt. Hab den PR dafür irgendwie übersehen.
