### ISSUE TITLE
Mails an Vorstandsmitglieder

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage#225]
Es sollte möglich sein von der Webseite Mails an Vorstandsmitglieder schicken zu können. So kann man Dokumente halbwegs unpersönlich halten und muss bei Neuwahlen nur die Vorstandsmitglieder aktualisieren.

Vielleicht löst man das einfach über Weiterleitungen wie z.B. wirtschaft@pep-dortmund.org, begabtenfoerderung@pep-dortmund.org und so weiter.

**Comment by bixel** [comment]
Was meinst du mit „von der Website verschicken“? Mmn reicht es, wenn die E-Mail-Adressen dort aufgelistet sind.

Vielleicht könnte man aus „Kontakt & Impressum“ zwei unterschiedliche Punkte machen und in der Kontakt Seite die Adressen auflisten, die interessant sein könnten.

**Comment by hmoldenhauer** [comment]
Ich fänd es gut, wenn man von der Seite https://pep-dortmund.org/ueber_uns/gremien.html direkt auf das jeweilige Gremium (also auf die Überschrift ) klicken könnte und dann eine Mail an das entsprechende Gremium schreiben könnte.
So sind dann nicht nur Gesichter und Namen auf der Webseite sondern man kann die Personen auch direkt kontaktieren.

**Comment by alexbirne** [comment]
Ich sehe das etwas anders (möglicherweise mit Überschneidungen zu Henning). Ich denke nicht, dass jedes Vorstandsmitglied direkt über die Seite erreichbar sein muss. Vielmehr finde ich dass wir das Funktionsprinzip, dass wir bereits teilweise nutzen (also Mailadresse für Soak, PhysiKon, Jobbörse, ...).
Das kann im Hintergrund dann gerne über ein Alias o.ä. weitergeleitet werden an die "private" Adresse, aber auf der Homepage würde ich diese privaten Mailadressen nicht veröffentlichen (davon ab, dass man die TU Adressen ja auch halbwegs gut raten kann ;) ).
Diese Funktionsadressen machen in einem gewissen Rahmen evtl. Sinn auf der Vorstandsseite integriert zu werden (z.B. kontakt@pep-dortmund.org für die GF) - aber ich würde da jedem VP (also auch wenn er von mehreren Personen besetzt wird) immer jeweils eine Funktionsadresse zuordnen, und nicht individuelle Personen "anschreibbar" machen.

**Comment by hmoldenhauer** [comment]
genau so meinte ich es :)

**Comment by bixel** [comment]
See #277 👍
