### ISSUE TITLE
Impressum

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage#234]
Das Impressum muss geupdated werden, Thorbens Adresse ist nicht mehr aktuell!

**Comment by bixel** [comment]
Assign party 😄

**Comment by bixel** [comment]
Nach [ein bisschen googlen](https://blog-it-recht.de/2009/05/15/impressumspflichten-nach-§-55-abs2-rstv/) bin ich der Meinung, dass wir den Teil zu "§ 55 Abs.2 RStV" komplett rausnehmen sollten. Unsere Website ist kein "journalistisch-redaktionell gestaltetes Angebot".

**Comment by hmoldenhauer** [comment]
Vermutlich hast du recht, wobei man "journalistisch-redaktionell gestaltetes Angebot" auch sehr weit fassen kann. Wenn ihr euch als Vorstand da einig seid, kann das gerne weg
