### ISSUE TITLE
old branches

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage#299]
@bixel Ich würde gerne die Branches auf der Webseite aufräumen, können die gelöscht werden?
Es handelt sich dabei um
- gh-pages
- matomo-analytics
- fine-tuning

**Comment by MaxNoe** [comment]
gh-pages auf jeden Fall.

 Zu den anderen muss @bixel was sagen.

**Comment by bixel** [comment]
Ehhhm die branches würde ich gern beide irgendwie und irgendwann zu einem Abschluss bringen. Ich schaue mir die die Tage noch mal an. Zumindest fine-tuning sollte schnell gemerged werden können.
