### ISSUE TITLE
homepage is listed as not secure in firefox

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage#306]
firefox blocks the homepage, based on:
https://support.mozilla.org/en-US/kb/what-does-your-connection-is-not-secure-mean?as=u&utm_source=inproduct

**Comment by Fresoquark** [comment]
Not just Firefox, happens when using Chrome as well

**Comment by bixel** [comment]
Looks like the certificate renewal didn’t work. I’ll fix it in a couple of minutes.

**Comment by bixel** [comment]
Done. The auto-renewal script was changed, (at least the uberspace docs differed from crontab).
