### ISSUE TITLE
Link to the Soak-special not working.

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/homepage#33]
The link of "Reinschauen" on the title page leads to an 404.

**Comment by jamueller** [comment]
Not in my case. It's working normally and leads you to the complete post.

**Comment by bixel** [comment]
This is not the case for the online-version. The link on https://pep-dortmund.github.io/towards-a-new-website/index.html is leading to https://pep-dortmund.github.io/special/sommerakademie/veranstaltungen/2016/04/28/soak2016-special.html

**Comment by MaxNoe** [comment]
Ah, so this seems to be a missing basepath somewhere

**Comment by MaxNoe** [comment]
I think here: https://github.com/pep-dortmund/towards-a-new-website/blob/master/index.html#L14

**Comment by jamueller** [comment]
I tried to figure out what's the problem, but I may don't have enough skills to do so 👎

**Comment by MaxNoe** [comment]
This is a problem only in the github preview because we the page is not at the root of the webserver.
