### ISSUE TITLE
Photos of Vorstand

### ISSUE THREAD

**Issue by jamueller** [pep-dortmund/homepage#35]
What about the photos? How should we do them?

I implemented for each position now dummy photos. 
Rows with just 2 or 1 person may look a little bit ugly.
Is it possible to center them somehow? 
My solutions did not work.

**Comment by hmoldenhauer** [comment]
@bixel and @jamueller could it be closed now? Guess the issue is solved

**Comment by jamueller** [comment]
yes, can be closed! Thanks for mentioning!
