### ISSUE TITLE
Typo in mailadress

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage#38]
The contact adress of PeP is wrong: it is kontak@pep-dortmund.org, but should be kontakt@pep-dortmund.org. It is right in the impressum, but wrong elsewhere

**Comment by hmoldenhauer** [comment]
changed typo in Mitmachen, but don't know if there are other mistakes. Please check

**Comment by MaxNoe** [comment]
Got fixed in #39 

If you have a commit message `Bla bla, fix #39` issues get closed automatically if the commit is merged into master.
