### ISSUE TITLE
Add Anmeldeformular to Homepage

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage#40]
There is no possibility to find our Anmeldeformular on our Homepage. It should be located under Mitmachen

**Comment by bixel** [comment]
Furthermore we want to have an online form. This will need some kind of server-side code running to store the form data.

**Comment by MaxNoe** [comment]
This got fixed in #42

**Comment by bixel** [comment]
Ok, a new issue for the online form might be smart :-P
