### ISSUE TITLE
Font change after Umlaut

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage#455]
The font size changes after an Umlaut appears in the text.
- Ubuntu 22.04
- Firefox 102.0

Chromium is fine, Smartphone as well (Firefox, Opera, Samsung Internet). 

![Screenshot from 2022-07-05 09-29-30](https://user-images.githubusercontent.com/32388722/177273803-310738f6-33a7-452b-8b9a-536bb3842ee4.png)

**Comment by jpherdi** [comment]
I cannot reproduce this with the same firefox version but Ubuntu 20.04.

As the `$font-family-base`: 
is set to `sans-serif`, it takes what ever sans-serif font you give it per default in your browser. Maybe you changed yours to something special? 
You can have a look in your firefox settings under Advanced:
![image](https://user-images.githubusercontent.com/41512963/177563551-fb049610-1875-42be-a922-dd35acb580ab.png)

Maybe you can try something else and check if this still comes up.
For me it actually looks quite different with the default font.

![image](https://user-images.githubusercontent.com/41512963/177563753-bc6b09e2-9ab6-404a-8c2d-f45bbd143135.png)

**Comment by jpherdi** [comment]
@chrbeckm ?

**Comment by chrbeckm** [comment]
Seems to be an one time occurence, couldn't reproduce it. Settings are the same as in your Screenshot.

**Comment by jpherdi** [comment]
Okay.
